version: '3.8'

services:

  backend:
    container_name: servgasapi
    image: devstoni/gastos-api:0.11.0
    environment:
      - 'spring.profiles.active=prod'
    ports:
      - '8081:8081'
    networks:
      - mysqldb
      - servgasops

  frontend:
    container_name: servgasfrnt
    image: devstoni/gastos-front:0.1.5
    ports:
      - 3001:3001
    stdin_open: true
    networks:
      - servgasops

networks:
  servgasops:
    external: false
  mysqldb:
    external: true
